name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore ./Bot.Presentation//Bot.Presentation.csproj
    - name: Test
      run: dotnet test ./Bot.IntegrationTests
    - name: Build
      run: dotnet build ./Bot.Presentation/Bot.Presentation.csproj --no-restore